@file:Suppress("HardcodedStringLiteral")

package com.example.adoption_and_childcare.network

/**
 * Constants for API endpoints and parameters.
 */
object ApiConstants {
    const val AUTHORIZATION = "Authorization"
    const val ID = "id"
    const val SINCE = "since"

    // Endpoints
    const val CHILDREN = "children"
    const val CHILD_BY_ID = "children/{id}"
    const val FAMILIES = "families"
    const val FAMILY_PROFILE = "family_profile"
    const val FAMILY_PROFILE_BY_ID = "family_profile/{id}"
    const val ADOPTION_APPLICATIONS = "adoption-applications"
    const val ADOPTION_APPLICATION_BY_ID = "adoption-applications/{id}"
    const val USERS = "users"
    const val PLACEMENTS = "placements"
    const val PLACEMENT_BY_ID = "placements/{id}"
    const val GUARDIANS = "guardians"
    const val GUARDIAN_BY_ID = "guardians/{id}"
    const val COURT_CASES = "court-cases"
    const val COURT_CASE_BY_ID = "court-cases/{id}"
    const val BACKGROUND_CHECKS = "background-checks"
    const val BACKGROUND_CHECK_BY_ID = "background-checks/{id}"
    const val FOSTER_TASKS = "foster-tasks"
    const val FOSTER_TASK_BY_ID = "foster-tasks/{id}"
    const val FOSTER_MATCHES = "foster-matches"
    const val FOSTER_MATCH_BY_ID = "foster-matches/{id}"
    const val PERMISSIONS = "permissions"
    const val PERMISSION_BY_ID = "permissions/{id}"
    const val USER_PERMISSIONS = "user-permissions"
    const val USER_PERMISSION_BY_ID = "user-permissions/{id}"
    const val SYSTEM_SETTINGS = "system-settings"
    const val SYSTEM_SETTING_BY_ID = "system-settings/{id}"
    const val DOCUMENTS = "documents"
    const val DOCUMENT_BY_ID = "documents/{id}"
    const val EDUCATION_RECORDS = "education-records"
    const val EDUCATION_RECORD_BY_ID = "education-records/{id}"
    const val MEDICAL_RECORDS = "medical-records"
    const val MEDICAL_RECORD_BY_ID = "medical-records/{id}"
    const val MONEY_RECORDS = "money-records"
    const val MONEY_RECORD_BY_ID = "money-records/{id}"
    const val HOME_STUDIES = "home-studies"
    const val HOME_STUDY_BY_ID = "home-studies/{id}"
    const val ANALYTICS_SUMMARY = "analytics/summary"
    const val LOGIN = "auth/login"
    const val REGISTER = "auth/register"
    const val NOTIFICATIONS = "notifications"
    const val UNREAD_NOTIFICATION_COUNT = "notifications/unread-count"
    const val MARK_NOTIFICATION_READ = "notifications/{id}/read"
    const val UPDATE_FCM_TOKEN = "auth/fcm-token"
    const val SYNC_PUSH = "api/v2/sync/push"
    const val SYNC_PULL = "api/v2/sync/pull"

    // JSON Field Names
    const val TABLE_NAME = "table_name"
    const val OPERATION = "operation"
    const val RECORD_ID = "record_id"
    const val PAYLOAD = "payload"
    const val MEDICAL_RECORDS_JSON = "medical_records"
    const val EDUCATION_RECORDS_JSON = "education_records"
    const val MONEY_RECORDS_JSON = "money_records"
    const val CASE_REPORTS_JSON = "case_reports"
    const val COURT_CASES_JSON = "court_cases"
    const val ADOPTION_APPLICATIONS_JSON = "adoption_applications"
    const val HOME_STUDIES_JSON = "home_studies"
    const val AUDIT_LOGS_JSON = "audit_logs"
    const val BACKGROUND_CHECKS_JSON = "background_checks"
    const val FOSTER_TASKS_JSON = "foster_tasks"
    const val FOSTER_MATCHES_JSON = "foster_matches"
    const val USER_PERMISSIONS_JSON = "user_permissions"
    const val SYSTEM_SETTINGS_JSON = "system_settings"
    const val SOS_LOCATIONS_JSON = "sos_locations"
    const val ACTION_ITEMS_JSON = "action_items"
    const val DASHBOARD_METRICS_JSON = "dashboard_metrics"
    const val DASHBOARD_PREFERENCES_JSON = "dashboard_preferences"
    const val CRITICAL_DATES_JSON = "critical_dates"
    const val WORKER_MESSAGES_JSON = "worker_messages"
    const val RISK_ASSESSMENTS_JSON = "risk_assessments"
    const val PERMANENCY_PLANS_JSON = "permanency_plans"
    const val CASE_URGENCY_FLAGS_JSON = "case_urgency_flags"
    const val CASE_ACTIVITIES_JSON = "case_activities"
    const val CASE_DEADLINES_JSON = "case_deadlines"
    const val CASE_APPROVALS_JSON = "case_approvals"
    const val PLACEMENT_COMPATIBILITY_JSON = "placement_compatibility"
    const val WORKLOAD_TRACKING_JSON = "workload_tracking"
    const val ID_NUMBER = "id_number"
    const val NATIONAL_ID_NO = "national_id_no"
    const val SUB_COUNTY = "sub_county"
    const val PLATFORM_ANDROID = "android"
}
